-- Your SQL goes here


CREATE TABLE "plans"(
	"id" INT4 NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR NOT NULL,
	"description" VARCHAR,
	"stripe_product_id" VARCHAR NOT NULL,
	"price" NUMERIC NOT NULL,
	"stripe_price_id" VARCHAR NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ
);

